name: Trigger auto deployment for container-app-taqqxkxui6sme

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '//**'
    - '.github/workflows/container-app-taqqxkxui6sme-AutoDeployTrigger-6860a547-fc3e-4dc2-aa5e-605b30765bce.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPTAQQXKXUI6SME_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPTAQQXKXUI6SME_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPTAQQXKXUI6SME_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPPTAQQXKXUI6SME_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPTAQQXKXUI6SME_REGISTRY_PASSWORD }}
          containerAppName: container-app-taqqxkxui6sme
          resourceGroup: reactbasic804aa58c
          imageToBuild: default/container-app-taqqxkxui6sme:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


